### PR TITLE
Duplicates the Lister.cs rather than linking to it. Flashes out the P…

### PR DESCRIPTION
**Pull request by philals**
…rogram.cs with a few more endpoints.

### CODE REVIEW

**Comment by MatthewSteeples** [comment]
This causes some tests to fail for some reason

**Comment by philals** [comment]
Checking into it...

**Comment by philals** [comment]
Do you know what tests? The Mock tests are going green for me. Are you looking at the fail in AppVeyor?

**Comment by MatthewSteeples** [comment]
Yeah, I think it may have been a transient error in AppVeyor actually. Looking into it. Will merge it when it goes green

**Pull request merged**
